import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#1b1b1d',
        'outline-variant': '#4b4454',
        'surface-container-lowest': '#0e0e10',
        'on-secondary-fixed-variant': '#004a77',
        'primary-container': '#a974ff',
        'inverse-on-surface': '#303032',
        'surface-variant': '#353437',
        'surface-container': '#201f21',
        'inverse-primary': '#7733d9',
        'surface-container-highest': '#353437',
        'tertiary-fixed-dim': '#ffb59d',
        'on-surface': '#e5e1e4',
        'primary-fixed': '#ecdcff',
        'on-surface-variant': '#cdc3d7',
        'tertiary-fixed': '#ffdbd0',
        'on-error-container': '#ffdad6',
        'surface-tint': '#d5baff',
        'on-tertiary-fixed': '#390c00',
        'on-background': '#e5e1e4',
        'on-tertiary-fixed-variant': '#832600',
        'error-container': '#93000a',
        'secondary-container': '#00a2fd',
        tertiary: '#ffb59d',
        'primary-fixed-dim': '#d5baff',
        'on-secondary-container': '#003558',
        'on-primary-container': '#39007a',
        secondary: '#98cbff',
        'surface-bright': '#39393b',
        'on-primary-fixed': '#270057',
        'on-tertiary': '#5d1900',
        'on-primary': '#42008a',
        background: '#131315',
        'secondary-fixed': '#cfe5ff',
        outline: '#968da0',
        'tertiary-container': '#f3632d',
        'surface-container-high': '#2a2a2c',
        primary: '#d5baff',
        'on-tertiary-container': '#511500',
        'surface-dim': '#131315',
        'on-error': '#690005',
        'inverse-surface': '#e5e1e4',
        surface: '#131315',
        'on-secondary-fixed': '#001d33',
        'on-primary-fixed-variant': '#5e02c0',
        'secondary-fixed-dim': '#98cbff',
        error: '#ffb4ab',
        'on-secondary': '#003354',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        lg: '40px',
        xl: '64px',
        base: '8px',
        xs: '4px',
        sm: '12px',
        'margin-desktop': '48px',
        gutter: '20px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'label-md': ['JetBrains Mono'],
        'headline-md': ['Hanken Grotesk'],
        'label-sm': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        display: ['Hanken Grotesk'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
